spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mysql_tst?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 2018
    driver-class-name: com.mysql.cj.jdbc.Driver
    #下面为连接池的补充设置，应用到上面所有数据源中
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #初始化大小，最小，最大
      initial-size: 1
      min-idle: 3
      max-active: 20
      #配置获取连接等待超时的时间
      maxWait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲链接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      #打开PSCache,并指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #配置监控统计拦截的filter,去掉后监控界面sql无法统计，'wall'用于防火墙
      filter: stat,wall,slf4j
      connection-properties: druid,stat.mergeSql=true;durid.stat.slowSqlMillis=5000
      #合并多个DuridDataSource的监控数据
      #use-global-data-source-stat: true


  mvc:
    favicon:
      enabled: false
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #
  typeAliasesPackage: com.teemo.bootdemo.entity

  configuration:
    cache-enabled: false
    map-underscore-to-camel-case: true

  global-config:
    #
    db-config:
      id-type: AUTO
      column-underline: true
      field-strategy: not_empty
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
  #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
